const productLink = '<a href="/san-pham">xem các sản phẩm chăm sóc tại nhà của MIÊN</a>'
const bookingLink = '<a href="/?dat-lich=1">đặt lịch tư vấn tại MIÊN</a>'

function article({ intro, answer, sections, checklist, caution, closing }) {
  return [
    `<p>${intro}</p>`,
    `<p><strong>${answer}</strong></p>`,
    ...sections.flatMap(section => [
      `<h2>${section.title}</h2>`,
      ...section.paragraphs.map(paragraph => `<p>${paragraph}</p>`),
    ]),
    '<h2>Cách thực hành đơn giản tại nhà</h2>',
    `<ul>${checklist.map(item => `<li>${item}</li>`).join('')}</ul>`,
    '<h2>Khi nào nên dừng và tìm hỗ trợ?</h2>',
    `<p>${caution}</p>`,
    `<blockquote>${closing}</blockquote>`,
    `<p>Bạn có thể ${productLink} hoặc ${bookingLink} nếu muốn xây dựng một chu trình phù hợp hơn với tình trạng hiện tại.</p>`,
  ].join('')
}

export const detailedPostSeeds = [
  {
    category: 'Chăm sóc sức khỏe',
    title: '7 cách ngủ ngon hơn sau một ngày căng thẳng',
    slug: '7-cach-ngu-ngon-hon-sau-mot-ngay-cang-thang',
    excerpt: 'Một chuỗi thói quen nhỏ giúp cơ thể giảm nhịp, dễ đi vào giấc ngủ và thức dậy nhẹ nhàng hơn.',
    metaTitle: '7 cách ngủ ngon hơn sau ngày căng thẳng | MIÊN Spa',
    metaDescription: 'Khám phá 7 cách ngủ ngon hơn: điều chỉnh ánh sáng, nhịp thở, nhiệt độ phòng và thói quen buổi tối để cơ thể nghỉ ngơi sâu hơn.',
    focusKeyword: 'cách ngủ ngon hơn',
    secondaryKeywords: ['thói quen trước khi ngủ', 'thư giãn buổi tối', 'giấc ngủ chất lượng'],
    content: article({
      intro: 'Khó ngủ sau một ngày bận rộn không nhất thiết có nghĩa là bạn thiếu mệt. Nhiều khi cơ thể đã mệt nhưng hệ thần kinh vẫn đang nhận tín hiệu phải tiếp tục cảnh giác từ ánh sáng mạnh, công việc dang dở và dòng thông tin liên tục trên màn hình.',
      answer: 'Cách ngủ ngon hơn là tạo một giai đoạn chuyển tiếp đều đặn từ thức sang nghỉ, bắt đầu trước giờ ngủ khoảng 60 phút và lặp lại vào phần lớn các ngày trong tuần.',
      sections: [
        { title: 'Giảm ánh sáng và tiếng ồn đúng thời điểm', paragraphs: ['Ánh sáng là một trong những tín hiệu quan trọng giúp đồng hồ sinh học phân biệt ngày và đêm. Trước giờ ngủ, hãy tắt bớt đèn trần, dùng nguồn sáng vàng dịu và giảm độ sáng màn hình. Nếu sống gần đường lớn, rèm cản sáng hoặc âm thanh nền đều có thể giúp không gian ổn định hơn.', 'Bạn không cần biến phòng ngủ thành nơi hoàn toàn im lặng. Điều quan trọng là tránh những âm thanh thay đổi đột ngột. Một tiếng quạt đều hoặc âm thanh tự nhiên ở mức nhỏ thường ít gây chú ý hơn tiếng thông báo điện thoại.'], },
        { title: 'Để cơ thể nhận ra tín hiệu nghỉ ngơi', paragraphs: ['Tắm nước ấm, ngâm chân trong 15 phút hoặc massage nhẹ vùng vai gáy là những hoạt động có nhịp chậm. Sau khi làm ấm, nhiệt độ cơ thể giảm dần và có thể hỗ trợ cảm giác buồn ngủ tự nhiên.', 'Hãy giữ các bước ngắn và quen thuộc: thay đồ thoải mái, chuẩn bị nước cho sáng hôm sau, viết ba việc cần làm vào giấy rồi khép sổ. Việc ghi lại giúp não bớt phải giữ danh sách công việc trong trí nhớ.'], },
        { title: 'Thở chậm thay vì cố ép mình ngủ', paragraphs: ['Khi nằm xuống, thử hít vào bằng mũi trong bốn nhịp và thở ra trong sáu nhịp. Nhịp thở ra dài hơn thường tạo cảm giác dịu. Thực hiện trong ba đến năm phút, không cần đếm thật chính xác và không nín thở nếu thấy khó chịu.', 'Nếu sau khoảng 20–30 phút vẫn tỉnh táo, hãy rời giường và làm một việc yên tĩnh dưới ánh sáng thấp. Quay lại khi buồn ngủ giúp giường tiếp tục gắn với cảm giác nghỉ thay vì bực bội.'], },
      ],
      checklist: ['Dừng caffeine ít nhất 6 giờ trước khi ngủ.', 'Đặt điện thoại ngoài tầm với hoặc bật chế độ không làm phiền.', 'Giữ giờ thức dậy tương đối ổn định, kể cả cuối tuần.', 'Ăn tối vừa đủ và tránh uống quá nhiều nước sát giờ ngủ.', 'Dành 5 phút thả lỏng hàm, vai và bàn tay.'],
      caution: 'Nếu mất ngủ kéo dài trên ba tuần, ảnh hưởng rõ đến công việc, tâm trạng hoặc đi kèm ngáy lớn, khó thở, đau ngực hay buồn ngủ quá mức ban ngày, bạn nên trao đổi với bác sĩ. Các thói quen thư giãn hỗ trợ giấc ngủ nhưng không thay thế chẩn đoán và điều trị.',
      closing: 'Một giấc ngủ tốt thường bắt đầu từ cách bạn khép lại ngày hôm đó, không chỉ từ khoảnh khắc đặt lưng xuống giường.',
    }),
  },
  {
    category: 'Chăm sóc sức khỏe',
    title: 'Massage vai gáy tại nhà: quy trình 10 phút an toàn',
    slug: 'massage-vai-gay-tai-nha-10-phut',
    excerpt: 'Hướng dẫn thả lỏng vùng cổ, vai và lưng trên bằng lực vừa phải, phù hợp sau thời gian ngồi lâu.',
    metaTitle: 'Massage vai gáy tại nhà trong 10 phút | MIÊN Spa',
    metaDescription: 'Học quy trình massage vai gáy tại nhà trong 10 phút với lực vừa phải, tư thế đúng và những trường hợp cần tránh massage.',
    focusKeyword: 'massage vai gáy tại nhà',
    secondaryKeywords: ['đau mỏi vai gáy', 'thả lỏng cổ vai', 'massage an toàn'],
    content: article({
      intro: 'Ngồi trước máy tính, cúi nhìn điện thoại và căng thẳng kéo dài thường khiến vai nâng lên mà chúng ta không nhận ra. Một buổi tự massage ngắn có thể làm vùng cơ ấm hơn, tăng cảm giác linh hoạt và nhắc cơ thể trở về tư thế dễ chịu.',
      answer: 'Massage vai gáy tại nhà nên dùng lực nhẹ đến vừa, di chuyển chậm trên phần cơ mềm và tránh ấn trực tiếp vào đốt sống, phía trước cổ hoặc vùng đang sưng đau.',
      sections: [
        { title: 'Chuẩn bị tư thế và làm ấm', paragraphs: ['Ngồi trên ghế có tựa, đặt hai bàn chân chạm sàn và thả lỏng hàm. Xoa hai lòng bàn tay cho ấm, sau đó áp lên vai trong vài nhịp thở. Nếu dùng dầu massage, chỉ cần một lượng nhỏ để tay không trượt quá nhanh.', 'Bắt đầu bằng cách nhún vai lên khi hít vào và thả xuống khi thở ra. Lặp lại năm lần. Xoay vai ra sau theo vòng tròn nhỏ, không cố tạo tiếng kêu ở khớp cổ.'], },
        { title: 'Quy trình 10 phút', paragraphs: ['Trong ba phút đầu, dùng lòng bàn tay vuốt từ chân tóc xuống vai. Ba phút tiếp theo, dùng các đầu ngón tay bóp nhẹ phần cơ phía trên vai, giữ mỗi điểm hai đến ba giây rồi thả. Luôn so sánh cảm giác hai bên để điều chỉnh lực.', 'Hai phút sau, đặt tay phải lên vai trái và thực hiện vòng tròn nhỏ ở vùng cơ cạnh bả vai; đổi bên. Hai phút cuối, đan tay sau gáy, tựa đầu nhẹ vào tay và hít thở chậm. Tay chỉ làm điểm tựa, không kéo cổ về phía trước.'], },
        { title: 'Giữ kết quả sau massage', paragraphs: ['Đứng lên đi lại một vài phút, uống nước theo nhu cầu và điều chỉnh màn hình ngang tầm mắt. Cứ mỗi 45–60 phút làm việc, hãy đổi tư thế thay vì cố giữ một tư thế được cho là hoàn hảo.', 'Cảm giác sau massage nên là ấm, nhẹ và dễ cử động hơn. Đau nhói, tê lan xuống tay hoặc chóng mặt là dấu hiệu cần dừng ngay.'], },
      ],
      checklist: ['Kiểm tra da không có vết thương hoặc viêm đỏ.', 'Giữ mức lực không quá 5 trên thang đau 10 điểm.', 'Thở đều trong suốt quá trình.', 'Không xoay hoặc bẻ cổ đột ngột.', 'Đi lại nhẹ nhàng sau khi hoàn thành.'],
      caution: 'Không tự massage vùng cổ vai khi vừa chấn thương, sốt, có dấu hiệu viêm cấp, loãng xương nặng hoặc đau lan kèm yếu tay. Nếu đau kéo dài, tái diễn thường xuyên hay xuất hiện sau va chạm, hãy gặp bác sĩ hoặc chuyên viên phục hồi chức năng.',
      closing: 'Lực mạnh không đồng nghĩa với hiệu quả cao; nhịp chậm và cảm giác an toàn mới giúp cơ thể chịu thả lỏng.',
    }),
  },
  {
    category: 'Chăm sóc sức khỏe',
    title: 'Ngâm chân nước ấm đúng cách để thư giãn buổi tối',
    slug: 'ngam-chan-nuoc-am-dung-cach',
    excerpt: 'Nhiệt độ, thời gian và các lưu ý giúp một chậu nước ấm trở thành nghi thức thư giãn đơn giản.',
    metaTitle: 'Ngâm chân nước ấm đúng cách buổi tối | MIÊN Spa',
    metaDescription: 'Hướng dẫn ngâm chân nước ấm đúng cách: nhiệt độ phù hợp, thời gian 15–20 phút, cách chăm sóc da chân và các trường hợp cần thận trọng.',
    focusKeyword: 'ngâm chân nước ấm đúng cách',
    secondaryKeywords: ['ngâm chân buổi tối', 'thư giãn bàn chân', 'chăm sóc chân'],
    content: article({
      intro: 'Sau một ngày đứng nhiều hoặc di chuyển liên tục, bàn chân thường là nơi giữ lại cảm giác nặng mỏi rõ nhất. Ngâm chân là một nghi thức ít dụng cụ, nhưng nhiệt độ quá cao hoặc thời gian quá dài có thể làm da khô và gây khó chịu.',
      answer: 'Ngâm chân nước ấm đúng cách là dùng nước khoảng 37–40°C trong 15–20 phút, mực nước qua mắt cá chân và lau khô kỹ sau khi kết thúc.',
      sections: [
        { title: 'Chọn nhiệt độ bằng cảm giác an toàn', paragraphs: ['Nếu không có nhiệt kế, thử nước bằng mặt trong cổ tay hoặc khuỷu tay trước khi cho chân vào. Nước nên ấm dễ chịu, không làm da đỏ nhanh và không gây cảm giác châm chích. Chuẩn bị một bình nước ấm riêng để thêm từng ít nếu nước nguội.', 'Muối khoáng hoặc thảo mộc tạo thêm trải nghiệm mùi hương nhưng không bắt buộc. Người có da nhạy cảm nên bắt đầu với nước sạch, tránh tinh dầu nguyên chất tiếp xúc trực tiếp với da.'], },
        { title: 'Biến 20 phút thành khoảng nghỉ thực sự', paragraphs: ['Ngồi trên ghế vững, lưng có điểm tựa. Trong vài phút đầu, cử động từng ngón chân và xoay cổ chân chậm. Sau đó để chân nghỉ, thở đều và tránh vừa ngâm vừa xử lý công việc trên điện thoại.', 'Khi kết thúc, lau kỹ kẽ ngón chân. Thoa một lớp kem dưỡng mỏng lên gót và mu bàn chân nếu da khô, nhưng hạn chế bôi nhiều giữa các kẽ vì độ ẩm kéo dài có thể khiến da dễ kích ứng.'], },
        { title: 'Tần suất phù hợp', paragraphs: ['Hai đến bốn buổi mỗi tuần thường đủ để duy trì một nghi thức thư giãn. Bạn có thể ngâm trước giờ ngủ khoảng 60–90 phút, kết hợp ánh sáng dịu và một cốc nước ấm nếu thích.', 'Ngâm chân không có tác dụng thải độc hay chữa bệnh như một số lời quảng cáo. Giá trị thực tế nằm ở cảm giác ấm, khoảng dừng có chủ ý và việc chăm sóc bàn chân thường xuyên.'], },
      ],
      checklist: ['Kiểm tra nhiệt độ trước khi ngâm.', 'Dùng chậu sạch và khăn riêng.', 'Đặt đồng hồ 15–20 phút.', 'Lau khô kỹ, nhất là kẽ ngón chân.', 'Quan sát vết nứt, đổi màu hoặc vùng da bất thường.'],
      caution: 'Người mắc đái tháo đường, giảm cảm giác ở chân, bệnh mạch máu ngoại biên, đang mang thai có biến chứng hoặc có vết thương hở nên hỏi nhân viên y tế trước. Dừng ngay nếu chóng mặt, bỏng rát hoặc da đổi màu bất thường.',
      closing: 'Một chậu nước ấm không cần cầu kỳ; nhiệt độ vừa đủ và 20 phút không bị gián đoạn đã là một khoảng chăm sóc đáng giá.',
    }),
  },
  {
    category: 'Hiểu về cơ thể',
    title: 'Dấu hiệu cơ thể đang cần nghỉ ngơi, không chỉ là buồn ngủ',
    slug: 'dau-hieu-co-the-can-nghi-ngoi',
    excerpt: 'Nhận biết những tín hiệu sớm của mệt mỏi thể chất và tinh thần để nghỉ trước khi cơ thể cạn năng lượng.',
    metaTitle: '9 dấu hiệu cơ thể đang cần nghỉ ngơi | MIÊN Spa',
    metaDescription: 'Nhận biết dấu hiệu cơ thể đang cần nghỉ ngơi qua khả năng tập trung, nhịp thở, căng cơ và cảm xúc; kèm cách phục hồi phù hợp.',
    focusKeyword: 'dấu hiệu cơ thể cần nghỉ ngơi',
    secondaryKeywords: ['mệt mỏi kéo dài', 'phục hồi năng lượng', 'nghỉ ngơi đúng cách'],
    content: article({
      intro: 'Buồn ngủ là tín hiệu dễ thấy, nhưng cơ thể thường báo mệt từ sớm bằng nhiều cách tinh tế hơn: đọc một đoạn nhiều lần vẫn không hiểu, vai tự động nhô lên, dễ cáu với tiếng động nhỏ hoặc thèm đồ ngọt liên tục.',
      answer: 'Dấu hiệu cơ thể cần nghỉ ngơi gồm giảm tập trung, căng cơ kéo dài, thay đổi cảm xúc, nhịp thở nông, hiệu suất giảm và cảm giác mệt không cải thiện dù vẫn cố làm thêm.',
      sections: [
        { title: 'Những tín hiệu thường bị bỏ qua', paragraphs: ['Khi não mệt, khả năng chuyển đổi giữa các nhiệm vụ chậm lại. Bạn có thể mở nhiều cửa sổ nhưng hoàn thành rất ít, quên những việc vừa định làm hoặc mắc lỗi đơn giản. Đây thường là lúc một khoảng nghỉ ngắn hiệu quả hơn thêm một cốc cà phê.', 'Cơ thể cũng biểu hiện qua hàm siết, trán nhíu, đau đầu âm ỉ, vai nặng và bàn tay lạnh. Nhịp thở trở nên ngắn khi áp lực kéo dài. Dừng lại để quan sát giúp bạn nhận tín hiệu trước khi nó phát triển thành đau rõ rệt.'], },
        { title: 'Chọn đúng loại nghỉ', paragraphs: ['Nếu mắt mỏi và đầu đầy thông tin, nghỉ khỏi màn hình có ích hơn nằm xuống lướt mạng. Nếu cơ thể trì trệ vì ngồi lâu, đi bộ chậm và vươn vai phù hợp hơn ngồi thêm. Nếu quá tải vì giao tiếp, vài phút yên tĩnh có thể phục hồi tốt hơn một cuộc trò chuyện khác.', 'Một khoảng nghỉ 5–10 phút nên có ranh giới rõ: đứng dậy, uống nước, nhìn xa, thở chậm hoặc ra ban công. Đặt thời gian kết thúc giúp bạn nghỉ mà không lo bị cuốn khỏi công việc.'], },
        { title: 'Xây nhịp nghỉ trước khi kiệt sức', paragraphs: ['Đừng chờ đến khi không thể tiếp tục mới nghỉ. Thử đánh dấu mức năng lượng từ 1 đến 10 vào ba thời điểm trong ngày. Sau một tuần, bạn sẽ thấy khung giờ thường xuống sức và có thể đặt khoảng nghỉ trước đó.', 'Giấc ngủ, bữa ăn đều, vận động và thời gian không làm việc tạo nên nền phục hồi. Một buổi spa có thể hỗ trợ thả lỏng, nhưng nhịp sinh hoạt hàng ngày mới quyết định cơ thể có đủ cơ hội hồi phục hay không.'], },
      ],
      checklist: ['Rời màn hình và nhìn xa trong 5 phút.', 'Thả vai, nới lỏng hàm và mở bàn tay.', 'Uống nước rồi kiểm tra cảm giác đói thật sự.', 'Chọn một việc quan trọng nhất cho phần thời gian còn lại.', 'Kết thúc công việc vào một giờ đã định.'],
      caution: 'Mệt mỏi kéo dài dù ngủ đủ, sụt cân không rõ nguyên nhân, khó thở, tim đập bất thường, đau ngực hoặc tâm trạng suy giảm nhiều tuần cần được đánh giá y tế. Không nên quy mọi triệu chứng cho căng thẳng.',
      closing: 'Nghỉ ngơi không phải phần thưởng sau khi hoàn thành mọi việc; đó là điều kiện để bạn tiếp tục làm những việc quan trọng một cách bền vững.',
    }),
  },
  {
    category: 'Chăm sóc tại nhà',
    title: 'Chu trình chăm sóc da tối giản cho người bận rộn',
    slug: 'chu-trinh-cham-soc-da-toi-gian',
    excerpt: 'Ba bước nền tảng giúp duy trì làn da ổn định mà không cần một kệ sản phẩm quá nhiều tầng.',
    metaTitle: 'Chu trình chăm sóc da tối giản 3 bước | MIÊN Spa',
    metaDescription: 'Xây dựng chu trình chăm sóc da tối giản với làm sạch, dưỡng ẩm và chống nắng; cách thêm hoạt chất mà không làm da quá tải.',
    focusKeyword: 'chu trình chăm sóc da tối giản',
    secondaryKeywords: ['skincare tối giản', 'chăm sóc da cơ bản', 'dưỡng da cho người bận'],
    content: article({
      intro: 'Một chu trình dài không bảo đảm làn da khỏe hơn. Khi thời gian ít hoặc da đang nhạy cảm, ba bước phù hợp và được duy trì đều thường hữu ích hơn nhiều sản phẩm thay đổi liên tục.',
      answer: 'Chu trình chăm sóc da tối giản gồm làm sạch dịu, dưỡng ẩm phù hợp và chống nắng phổ rộng vào ban ngày; hoạt chất chỉ nên được thêm từng loại khi da đã ổn định.',
      sections: [
        { title: 'Buổi sáng: bảo vệ là ưu tiên', paragraphs: ['Nếu da không nhiều dầu, bạn có thể rửa bằng nước hoặc sữa rửa mặt dịu. Tiếp theo là kem dưỡng mỏng tùy nhu cầu và kem chống nắng SPF 30 trở lên. Thoa đủ cho mặt, tai và cổ; thoa lại khi ở ngoài trời lâu, đổ mồ hôi hoặc lau mặt.', 'Không cần xếp nhiều lớp serum chỉ vì mỗi sản phẩm có một công dụng riêng. Hãy đánh giá cảm giác da vào giữa ngày: quá bóng, căng hay dễ cay mắt để điều chỉnh kết cấu sản phẩm.'], },
        { title: 'Buổi tối: làm sạch và phục hồi', paragraphs: ['Tẩy trang khi dùng mỹ phẩm chống nước hoặc trang điểm, sau đó dùng sữa rửa mặt. Massage nhẹ trong khoảng 30–60 giây; chà lâu không làm lỗ chân lông sạch hơn và có thể tăng kích ứng.', 'Thoa kem dưỡng khi da còn hơi ẩm. Với vùng khô, có thể thêm một lớp mỏng ở đúng vị trí thay vì dùng sản phẩm nặng cho toàn mặt. Duy trì chu trình này hai tuần trước khi đánh giá.'], },
        { title: 'Thêm hoạt chất một cách có kiểm soát', paragraphs: ['Chỉ thêm một sản phẩm mới mỗi lần và dùng với tần suất thấp trong tuần đầu. Ghi lại ngày dùng cùng phản ứng của da. Điều này giúp nhận ra nguyên nhân nếu xuất hiện khô, đỏ hoặc nổi mụn.', 'Vitamin C, retinoid và acid có thể hữu ích nhưng không bắt buộc cho mọi người. Tình trạng da, thai kỳ, thuốc đang dùng và khả năng chống nắng đều ảnh hưởng đến lựa chọn.'], },
      ],
      checklist: ['Giữ một sản phẩm làm sạch dịu.', 'Chọn kem dưỡng không gây khó chịu sau 15 phút.', 'Dùng chống nắng mỗi sáng.', 'Thử sản phẩm mới trên vùng nhỏ.', 'Chụp ảnh da dưới cùng ánh sáng mỗi hai tuần.'],
      caution: 'Nếu da sưng, rát kéo dài, nổi mụn viêm nhiều, có dấu hiệu nhiễm trùng hoặc phản ứng sau sản phẩm mới, hãy ngừng dùng và gặp bác sĩ da liễu. Không tự xử lý tổn thương nặng bằng cách tăng nồng độ hoạt chất.',
      closing: 'Chu trình tốt là chu trình bạn hiểu, làn da chịu được và bạn có thể duy trì trong những ngày bận nhất.',
    }),
  },
  {
    category: 'Chăm sóc tại nhà',
    title: 'Da nhạy cảm nên chăm sóc thế nào khi thời tiết thay đổi?',
    slug: 'da-nhay-cam-khi-thoi-tiet-thay-doi',
    excerpt: 'Cách điều chỉnh làm sạch, dưỡng ẩm và môi trường sống khi da dễ đỏ rát trong giai đoạn giao mùa.',
    metaTitle: 'Chăm sóc da nhạy cảm khi thời tiết thay đổi',
    metaDescription: 'Hướng dẫn chăm sóc da nhạy cảm khi thời tiết thay đổi: giảm kích thích, phục hồi hàng rào da và nhận biết lúc cần khám da liễu.',
    focusKeyword: 'chăm sóc da nhạy cảm',
    secondaryKeywords: ['da nhạy cảm giao mùa', 'phục hồi hàng rào da', 'da đỏ rát'],
    content: article({
      intro: 'Nhiệt độ, độ ẩm, máy điều hòa và mức ô nhiễm thay đổi có thể khiến da vốn ổn định trở nên căng, ngứa hoặc đỏ. Lúc này, việc thêm nhiều sản phẩm “cấp cứu” cùng lúc thường làm khó xác định nguyên nhân.',
      answer: 'Chăm sóc da nhạy cảm khi thời tiết thay đổi nên tập trung giảm kích thích, làm sạch nhẹ, dưỡng ẩm nhiều lớp mỏng và tạm dừng các hoạt chất có nguy cơ gây khô rát.',
      sections: [
        { title: 'Nhận biết da đang bị kích ứng', paragraphs: ['Da nhạy cảm có thể châm chích ngay khi thoa sản phẩm quen thuộc, đỏ sau khi rửa, bong mịn quanh miệng hoặc ngứa khi đổ mồ hôi. Hãy ghi lại thời điểm xuất hiện và sản phẩm đã dùng thay vì vội kết luận dị ứng.', 'Giảm nhiệt độ nước rửa mặt, không dùng khăn chà và tránh xông hơi quá lâu. Nếu ở phòng điều hòa nhiều, một lớp dưỡng ẩm bổ sung vào vùng khô thường thực tế hơn xịt khoáng liên tục mà không khóa ẩm.'], },
        { title: 'Chu trình phục hồi trong 7–14 ngày', paragraphs: ['Giữ sữa rửa mặt dịu, kem dưỡng có thành phần hỗ trợ hàng rào da và chống nắng. Tạm dừng tẩy tế bào chết, retinoid, hương liệu mới cùng các dụng cụ làm sạch cơ học. Khi da hết châm chích ít nhất vài ngày, đưa từng sản phẩm trở lại với tần suất thấp.', 'Thử kem dưỡng ở một vùng nhỏ gần hàm trong hai đến ba ngày. Thành phần đơn giản không có nghĩa là chắc chắn không dị ứng, nhưng danh sách ngắn giúp dễ theo dõi phản ứng hơn.'], },
        { title: 'Điều chỉnh môi trường quanh da', paragraphs: ['Giặt vỏ gối đều, vệ sinh điện thoại và tránh để luồng điều hòa thổi trực tiếp vào mặt. Khi ra ngoài, mũ rộng vành và bóng râm giúp giảm phụ thuộc hoàn toàn vào một sản phẩm chống nắng.', 'Giấc ngủ thiếu và căng thẳng có thể làm cảm giác ngứa khó chịu hơn. Dành một nhịp thở chậm trước khi chăm sóc da cũng giúp bạn thao tác nhẹ tay và quan sát rõ hơn.'], },
      ],
      checklist: ['Rửa mặt bằng nước mát hoặc ấm nhẹ.', 'Tạm dừng sản phẩm gây châm chích.', 'Dưỡng ẩm ngay sau khi rửa.', 'Che nắng bằng nhiều biện pháp.', 'Ghi lại phản ứng và ngày bắt đầu.'],
      caution: 'Sưng môi hoặc mắt, khó thở, nổi mề đay toàn thân cần hỗ trợ y tế khẩn cấp. Với ban đỏ lan rộng, rỉ dịch, đau hoặc kéo dài, hãy gặp bác sĩ da liễu thay vì tiếp tục thử sản phẩm mới.',
      closing: 'Khi da nhạy cảm, bớt đi vài bước thường là cách nhanh nhất để nghe rõ điều làn da đang cần.',
    }),
  },
  {
    category: 'Chăm sóc sức khỏe',
    title: '5 bài thở thư giãn dễ thực hành trong ngày',
    slug: '5-bai-tho-thu-gian-de-thuc-hanh',
    excerpt: 'Năm cách điều chỉnh nhịp thở trong vài phút để tạo khoảng dừng giữa công việc và sinh hoạt.',
    metaTitle: '5 bài thở thư giãn dễ thực hành | MIÊN Spa',
    metaDescription: 'Thực hành 5 bài thở thư giãn đơn giản trong 1–5 phút, phù hợp giữa giờ làm việc, trước khi ngủ hoặc khi cần lấy lại bình tĩnh.',
    focusKeyword: 'bài thở thư giãn',
    secondaryKeywords: ['thở chậm', 'giảm căng thẳng', 'bài tập hít thở'],
    content: article({
      intro: 'Hơi thở luôn ở đó, nhưng khi căng thẳng chúng ta thường thở nhanh và nông mà không nhận ra. Một bài thở ngắn không xóa nguyên nhân gây áp lực, nhưng có thể tạo khoảng dừng đủ để cơ thể bớt căng và bạn chọn bước tiếp theo rõ ràng hơn.',
      answer: 'Bài thở thư giãn hiệu quả nhất là bài không gây hụt hơi hoặc chóng mặt, có nhịp thở ra dài và được thực hành trong tư thế thoải mái từ một đến năm phút.',
      sections: [
        { title: 'Ba bài thở cho ban ngày', paragraphs: ['Bài một là thở ra dài: hít vào bốn nhịp, thở ra sáu nhịp, lặp mười lần. Bài hai là thở hình hộp nhẹ: hít bốn, giữ hai, thở bốn, nghỉ hai; bỏ phần giữ nếu khó chịu. Bài ba là thở đếm lùi: mỗi lần thở ra đếm từ mười về một.', 'Bạn có thể thực hiện ngay tại bàn làm việc. Đặt hai chân xuống sàn, nới lỏng quần áo chật và để bụng chuyển động tự nhiên. Vai không cần nâng lên khi hít vào.'], },
        { title: 'Hai bài thở trước khi nghỉ', paragraphs: ['Thở cùng chuyển động: hít vào khi đưa tay sang ngang, thở ra khi ôm nhẹ hai vai. Lặp năm đến tám lần. Bài cuối là tiếng thở dài sinh lý nhẹ: hít vào, bổ sung một nhịp hít ngắn rồi thở ra chậm; chỉ lặp một đến ba lần.', 'Sau bài thở, ngồi yên vài nhịp để nhận biết cảm giác ở hàm, vai, ngực và bụng. Mục tiêu không phải đạt trạng thái hoàn toàn bình tĩnh mà là nhận ra một thay đổi nhỏ.'], },
        { title: 'Biến việc thở thành thói quen', paragraphs: ['Gắn bài tập với một mốc sẵn có như trước cuộc họp, sau khi đóng máy tính hoặc lúc lên giường. Thực hành khi tương đối bình thường giúp bạn dễ nhớ cách dùng hơn trong lúc áp lực.', 'Không cần cố hít thật sâu vì hít quá nhiều có thể gây chóng mặt. Hơi thở êm, nhỏ và thoải mái thường phù hợp hơn một nhịp thật lớn.'], },
      ],
      checklist: ['Chọn tư thế có điểm tựa.', 'Nới lỏng hàm và vai.', 'Bắt đầu bằng 60 giây.', 'Dừng nếu thấy chóng mặt hoặc tê.', 'Thực hành vào cùng một mốc mỗi ngày.'],
      caution: 'Bài thở không thay thế điều trị rối loạn lo âu, bệnh hô hấp hoặc tim mạch. Người đang có khó thở mới xuất hiện, đau ngực, ngất hoặc triệu chứng nghiêm trọng cần tìm hỗ trợ y tế thay vì cố kiểm soát bằng bài tập.',
      closing: 'Bạn không cần một căn phòng hoàn hảo để nghỉ; đôi khi ba lần thở ra chậm đã đủ mở ra một khoảng trống nhỏ trong ngày.',
    }),
  },
  {
    category: 'Hiểu về cơ thể',
    title: 'Cách phục hồi cơ thể sau khi ngồi làm việc cả ngày',
    slug: 'phuc-hoi-co-the-sau-khi-ngoi-lau',
    excerpt: 'Một kế hoạch cuối ngày giúp hông, lưng, vai và mắt chuyển động trở lại sau nhiều giờ ngồi.',
    metaTitle: 'Phục hồi cơ thể sau khi ngồi lâu | MIÊN Spa',
    metaDescription: 'Kế hoạch phục hồi cơ thể sau khi ngồi lâu với vận động nhẹ, giãn cơ, thư giãn mắt và điều chỉnh góc làm việc dễ áp dụng.',
    focusKeyword: 'phục hồi cơ thể sau khi ngồi lâu',
    secondaryKeywords: ['đau mỏi do ngồi lâu', 'giãn cơ văn phòng', 'thả lỏng cuối ngày'],
    content: article({
      intro: 'Cơ thể không được thiết kế để giữ yên một tư thế trong nhiều giờ. Dù ghế tốt và bàn đúng độ cao, thiếu chuyển động vẫn có thể khiến hông cứng, lưng mỏi, mắt khô và đầu nặng vào cuối ngày.',
      answer: 'Phục hồi cơ thể sau khi ngồi lâu cần kết hợp đi bộ nhẹ, vận động khớp trong tầm thoải mái và thay đổi thói quen trong ngày; một lần kéo giãn mạnh không thể bù hoàn toàn cho tám giờ ít di chuyển.',
      sections: [
        { title: 'Mười phút chuyển trạng thái sau giờ làm', paragraphs: ['Bắt đầu bằng hai phút đi lại quanh nhà, vung tay tự nhiên. Tiếp theo đứng bám vào ghế, đưa hông sang hai bên và gập duỗi gối nhẹ. Động tác nhỏ giúp cơ thể làm quen với chuyển động trước khi kéo giãn.', 'Dành ba phút cho phần thân trên: xoay vai, mở hai tay sang ngang, nghiêng người sang bên. Kết thúc bằng cách nằm ngửa, kê chân lên ghế trong ba phút và thở đều.'], },
        { title: 'Đừng quên mắt và bàn tay', paragraphs: ['Mỗi 20 phút, nhìn một vật ở xa trong khoảng 20 giây và chớp mắt chậm. Cuối ngày, xoa ấm lòng bàn tay rồi che nhẹ lên mắt nhắm, không ấn vào nhãn cầu.', 'Xòe rộng các ngón tay, xoay cổ tay và lắc nhẹ bàn tay. Nếu dùng chuột nhiều, đổi vị trí thiết bị gần cơ thể hơn để khuỷu tay không phải với ra trước.'], },
        { title: 'Thiết kế ngày làm việc có chuyển động', paragraphs: ['Đặt chai nước ở vị trí buộc bạn phải đứng dậy. Chuyển một cuộc gọi ngắn thành thời gian đi bộ. Thay đổi giữa ngồi tựa lưng, ngồi thẳng và đứng trong thời lượng vừa phải.', 'Mục tiêu là đa dạng tư thế, không giữ một “tư thế chuẩn” cứng nhắc. Cơ thể thích chuyển động thường xuyên hơn sự hoàn hảo kéo dài.'], },
      ],
      checklist: ['Đi bộ nhẹ 2–5 phút sau khi đóng máy.', 'Chuyển động hông và vai trong tầm không đau.', 'Nhìn xa và chớp mắt có chủ ý.', 'Đặt báo nhắc đổi tư thế mỗi giờ.', 'Sắp bàn phím và chuột gần cơ thể.'],
      caution: 'Đau lưng hoặc cổ kèm tê, yếu tay chân, mất kiểm soát đại tiểu tiện, sốt hoặc xuất hiện sau chấn thương cần được khám sớm. Không kéo giãn qua cơn đau nhói hoặc cố bẻ khớp để tạo tiếng kêu.',
      closing: 'Tư thế tốt nhất thường là tư thế tiếp theo; hãy để cơ thể được thay đổi thay vì bắt nó đứng yên thật đúng.',
    }),
  },
  {
    category: 'Chăm sóc tại nhà',
    title: 'Chăm sóc cơ thể mùa nóng mà không gây bí da',
    slug: 'cham-soc-co-the-mua-nong-khong-bi-da',
    excerpt: 'Làm sạch mồ hôi, dưỡng ẩm đúng lúc và chọn kết cấu phù hợp cho khí hậu nóng ẩm.',
    metaTitle: 'Chăm sóc cơ thể mùa nóng không bí da | MIÊN Spa',
    metaDescription: 'Cách chăm sóc cơ thể mùa nóng: làm sạch sau mồ hôi, dưỡng ẩm kết cấu nhẹ, chống nắng và hạn chế viêm nang lông do bí da.',
    focusKeyword: 'chăm sóc cơ thể mùa nóng',
    secondaryKeywords: ['dưỡng thể không bí da', 'da cơ thể mùa hè', 'viêm nang lông'],
    content: article({
      intro: 'Khí hậu nóng ẩm khiến nhiều người bỏ hẳn dưỡng thể vì sợ dính. Tuy nhiên, tắm nhiều, điều hòa và nắng vẫn có thể làm hàng rào da mất nước. Điều cần thay đổi thường là kết cấu và thời điểm, không phải ngừng chăm sóc hoàn toàn.',
      answer: 'Chăm sóc cơ thể mùa nóng nên ưu tiên làm sạch mồ hôi sớm, tắm nước mát, dùng dưỡng thể mỏng trên da hơi ẩm và thay quần áo thoáng sau vận động.',
      sections: [
        { title: 'Làm sạch đủ, không tẩy quá mức', paragraphs: ['Sau khi đổ mồ hôi nhiều, hãy thay quần áo và tắm khi có thể. Tập trung sản phẩm làm sạch ở vùng nách, bẹn, bàn chân và nơi có kem chống nắng; các vùng còn lại không cần chà xát mạnh.', 'Tẩy tế bào chết cơ học thường xuyên có thể tạo tổn thương nhỏ, đặc biệt khi da đã nóng đỏ. Nếu dùng sản phẩm hỗ trợ viêm nang lông, bắt đầu tần suất thấp và tránh dùng ngay sau cạo.'], },
        { title: 'Dưỡng ẩm theo vùng', paragraphs: ['Gel-cream hoặc lotion mỏng phù hợp cho tay chân, trong khi gót chân và khuỷu tay có thể cần kem đặc hơn. Thoa sau tắm khi da còn hơi ẩm rồi chờ vài phút trước khi mặc đồ.', 'Dầu cơ thể chỉ cần vài giọt và nên áp lên da ẩm. Nếu xuất hiện mụn li ti ở lưng hoặc ngực, tạm dừng sản phẩm mới, ưu tiên quần áo thoáng và theo dõi.'], },
        { title: 'Bảo vệ vùng da phơi nắng', paragraphs: ['Thoa chống nắng lên cổ, vai, cánh tay, bàn tay và chân khi các vùng này lộ ra ngoài. Quần áo, ô và bóng râm giúp giảm lượng sản phẩm phải thoa lại.', 'Giặt quần áo tập sau mỗi lần dùng và tránh ngồi lâu trong đồ còn ẩm. Đây là bước đơn giản nhưng ảnh hưởng rõ đến cảm giác bí và ma sát trên da.'], },
      ],
      checklist: ['Thay đồ ẩm sớm sau vận động.', 'Tắm nước mát hoặc ấm nhẹ.', 'Dưỡng thể mỏng trên da còn ẩm.', 'Dùng chất dưỡng đặc chỉ ở vùng khô.', 'Che nắng cho cả tay, cổ và chân.'],
      caution: 'Các nốt đỏ đau, có mủ, lan nhanh hoặc kèm sốt cần được bác sĩ đánh giá. Không tự nặn tổn thương hoặc dùng thuốc bôi chứa kháng sinh, corticoid khi chưa có hướng dẫn.',
      closing: 'Trong mùa nóng, cảm giác nhẹ trên da đến từ việc chọn đúng lượng và đúng vùng hơn là bỏ qua dưỡng ẩm.',
    }),
  },
  {
    category: 'Chăm sóc sức khỏe',
    title: 'Nghi thức buổi sáng 15 phút để bắt đầu ngày nhẹ hơn',
    slug: 'nghi-thuc-buoi-sang-15-phut',
    excerpt: 'Một lịch trình ngắn kết hợp ánh sáng, nước, chuyển động và định hướng ngày mới mà không cần dậy quá sớm.',
    metaTitle: 'Nghi thức buổi sáng 15 phút nhẹ nhàng | MIÊN Spa',
    metaDescription: 'Gợi ý nghi thức buổi sáng 15 phút gồm ánh sáng tự nhiên, uống nước, vận động nhẹ và chọn ưu tiên để bắt đầu ngày ổn định.',
    focusKeyword: 'nghi thức buổi sáng',
    secondaryKeywords: ['thói quen buổi sáng', 'bắt đầu ngày mới', 'chăm sóc sức khỏe hàng ngày'],
    content: article({
      intro: 'Một buổi sáng có chủ ý không cần bắt đầu lúc 5 giờ hay chứa một danh sách dài. Mười lăm phút đủ để cơ thể nhận ánh sáng, khớp được chuyển động và tâm trí biết điều gì cần ưu tiên.',
      answer: 'Nghi thức buổi sáng bền vững nên ngắn, có thứ tự rõ và phù hợp cả ngày bận: mở rèm, uống nước theo nhu cầu, vận động nhẹ rồi xác định một việc quan trọng.',
      sections: [
        { title: 'Năm phút đầu: ánh sáng và nước', paragraphs: ['Mở rèm hoặc ra ban công để nhận ánh sáng tự nhiên. Đây là tín hiệu giúp đồng hồ sinh học bắt đầu ngày. Nếu trời nắng gắt, đứng ở nơi có bóng râm và không nhìn trực tiếp vào mặt trời.', 'Uống một cốc nước nếu thấy khát. Không cần ép lượng lớn hoặc thêm nhiều nguyên liệu. Sau một đêm, cảm giác khô miệng là lời nhắc đơn giản để bù nước.'], },
        { title: 'Năm phút chuyển động', paragraphs: ['Đi lại quanh phòng, xoay vai, nâng hạ gót chân và ngồi xuống đứng lên từ ghế. Chọn biên độ vừa phải; mục tiêu là đánh thức cơ thể chứ không hoàn thành một buổi tập nặng.', 'Nếu lưng cứng, chống tay lên bàn và đưa hông ra sau, giữ cột sống dài trong vài nhịp. Nếu chóng mặt khi mới thức, hãy ngồi lại và đứng lên chậm.'], },
        { title: 'Năm phút định hướng ngày mới', paragraphs: ['Viết một việc quan trọng, một việc có thể hoãn và một khoảng nghỉ dự kiến. Ba dòng này tạo ranh giới tốt hơn một danh sách dài không có thứ tự.', 'Trì hoãn việc đọc thông báo cho đến khi hoàn thành nghi thức nếu có thể. Bạn sẽ bắt đầu ngày bằng tín hiệu của chính mình thay vì phản ứng ngay với yêu cầu từ bên ngoài.'], },
      ],
      checklist: ['Chuẩn bị cốc nước từ tối hôm trước.', 'Mở rèm ngay sau khi thức.', 'Chuyển động các khớp lớn trong 5 phút.', 'Viết một ưu tiên chính.', 'Đặt trước một khoảng nghỉ trong ngày.'],
      caution: 'Nếu thường xuyên chóng mặt, ngất, đau đầu dữ dội hoặc mệt kiệt sức vào buổi sáng dù ngủ đủ, hãy trao đổi với bác sĩ. Đừng cố thực hiện vận động khi cơ thể báo hiệu không an toàn.',
      closing: 'Một buổi sáng nhẹ không đến từ việc làm thật nhiều, mà từ vài tín hiệu rõ ràng giúp cơ thể biết ngày mới đã bắt đầu.',
    }),
  },
]
