<script setup lang="ts">
import { formatPrice } from '~/utils/currency'

definePageMeta({ layout: 'admin' })
const route = useRoute()
type OrderDetail = { id: number; reference: string; status: string; statusLabel: string; paymentStatusLabel: string; fulfillmentStatus: string; fulfillmentStatusLabel: string; customerName: string | null; customerPhone: string | null; customerEmail: string | null; customerNote: string | null; shippingAddressLine: string | null; shippingWard: string | null; shippingDistrict: string | null; shippingProvince: string | null; paymentMethod: string; subtotal: number; shippingFee: number; totalAmount: number; reservationExpiresAt: string | null; createdAt: string; items: Array<{ id: number; sku: string; productName: string; quantity: number; unitPrice: number; totalAmount: number }>; history: Array<{ id: number; status: string; note: string | null; createdAt: string }> }
const { data: response, pending, error, refresh } = await useAsyncData(`admin-order-${route.params.id}`, () => $fetch<{ data: OrderDetail }>(`/api/admin/orders/${route.params.id}`))
const order = computed(() => response.value?.data)
const mutating = ref(false)
const mutationError = ref('')
const cancellationReason = ref('')
useHead({ title: () => order.value ? `${order.value.reference} | MIÊN Admin` : 'Đơn hàng | MIÊN Admin' })

function failureMessage(value: unknown) { const failure = value as { data?: { statusMessage?: string }; statusMessage?: string }; return failure.data?.statusMessage ?? failure.statusMessage ?? 'Không thể cập nhật đơn hàng.' }
async function action(path: string, body?: Record<string, unknown>) { mutating.value = true; mutationError.value = ''; try { await $fetch(`/api/admin/orders/${route.params.id}/${path}`, { method: 'POST', body }); await refresh() } catch (failure) { mutationError.value = failureMessage(failure) } finally { mutating.value = false } }
const address = computed(() => order.value ? [order.value.shippingAddressLine, order.value.shippingWard, order.value.shippingDistrict, order.value.shippingProvince].filter(Boolean).join(', ') : '')
</script>

<template>
  <section class="mx-auto w-full max-w-[1250px] px-5 py-8 md:px-8 md:py-10 lg:px-10 lg:py-12"><NuxtLink to="/admin/don-hang" class="admin-inline-link"><AppIcon name="arrow-left" :size="15" /> Danh sách đơn</NuxtLink><div v-if="pending" class="mt-8 h-80 animate-pulse bg-[#e3dfd5]" /><div v-else-if="error || !order" class="mt-8 border-l-2 border-[#98675c] bg-[#efe0da] px-5 py-4 text-xs text-[#784b43]">Không thể tải đơn hàng.</div><template v-else><header class="mt-7 flex flex-col gap-6 border-b border-[#78816f]/20 pb-8 lg:flex-row lg:items-end lg:justify-between"><div><p class="text-[0.63rem] font-semibold uppercase tracking-[0.18em] text-[#73806d]">{{ order.reference }}</p><h1 class="mt-3 text-3xl font-semibold tracking-[-0.045em] md:text-4xl">{{ order.customerName }}</h1><div class="mt-4 flex flex-wrap gap-2"><StatusBadge :label="order.statusLabel" /><StatusBadge :label="order.fulfillmentStatusLabel" /><StatusBadge :label="order.paymentStatusLabel" /></div></div><div v-if="order.status === 'confirmed'" class="flex flex-wrap gap-2"><AppButton v-if="order.fulfillmentStatus === 'unfulfilled'" label="Bắt đầu đóng gói" :disabled="mutating" @click="action('fulfillment', { status: 'packing' })" /><AppButton v-if="order.fulfillmentStatus === 'packing'" label="Đã bàn giao vận chuyển" :disabled="mutating" @click="action('fulfillment', { status: 'shipped' })" /><AppButton label="Hoàn tất & trừ kho" icon="check" :disabled="mutating" @click="action('pay')" /></div></header><p v-if="mutationError" class="mt-5 border-l-2 border-[#98675c] bg-[#efe0da] px-5 py-4 text-xs text-[#784b43]">{{ mutationError }}</p>
      <div class="grid gap-12 py-9 lg:grid-cols-[minmax(0,1fr)_340px]"><div><h2 class="text-sm font-semibold">Sản phẩm</h2><div class="mt-5 divide-y divide-[#78816f]/18 border-y border-[#78816f]/18"><div v-for="item in order.items" :key="item.id" class="grid grid-cols-[1fr_auto] gap-5 py-5 text-xs"><div><strong class="text-sm">{{ item.productName }}</strong><p class="mt-1 text-[#747b70]">{{ item.sku }} · {{ formatPrice(item.unitPrice) }} × {{ item.quantity }}</p></div><strong>{{ formatPrice(item.totalAmount) }}</strong></div></div><h2 class="mt-10 text-sm font-semibold">Lịch sử xử lý</h2><div class="mt-5 divide-y divide-[#78816f]/15 border-y border-[#78816f]/15"><div v-for="entry in order.history" :key="entry.id" class="grid gap-1 py-4 text-xs sm:grid-cols-[150px_1fr]"><time class="text-[#7b8278]">{{ new Intl.DateTimeFormat('vi-VN', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(entry.createdAt)) }}</time><div><strong>{{ entry.status }}</strong><p v-if="entry.note" class="mt-1 text-[#6c7368]">{{ entry.note }}</p></div></div></div></div><aside class="space-y-8 border-t border-[#78816f]/20 pt-6 lg:border-l lg:border-t-0 lg:pl-8 lg:pt-0"><div><h2 class="text-sm font-semibold">Người nhận</h2><p class="mt-3 text-xs leading-6">{{ order.customerName }}<br>{{ order.customerPhone }}<br>{{ order.customerEmail || 'Không có email' }}<br>{{ address }}</p><p v-if="order.customerNote" class="mt-3 text-xs italic text-[#737a70]">{{ order.customerNote }}</p></div><div><h2 class="text-sm font-semibold">Thanh toán</h2><div class="mt-3 grid gap-2 text-xs"><div class="flex justify-between"><span>Tạm tính</span><span>{{ formatPrice(order.subtotal) }}</span></div><div class="flex justify-between"><span>Giao hàng</span><span>{{ formatPrice(order.shippingFee) }}</span></div><div class="flex justify-between border-t border-[#78816f]/20 pt-3 text-sm"><strong>Tổng cộng</strong><strong>{{ formatPrice(order.totalAmount) }}</strong></div></div></div><div v-if="order.status === 'confirmed' && order.fulfillmentStatus !== 'shipped'" class="border-t border-[#78816f]/20 pt-6"><label class="admin-field">Lý do hủy<textarea v-model="cancellationReason" rows="3" placeholder="Nhập lý do để lưu lịch sử" /></label><AppButton label="Hủy đơn & trả tồn" variant="secondary" class="mt-3 w-full" :disabled="mutating || !cancellationReason.trim()" @click="action('cancel', { reason: cancellationReason })" /></div></aside></div></template></section>
</template>
